using Test
using VelocityDistributionFunctions
using LinearAlgebra
using Serialization
using Base.Threads
using Downloads
using Chairmarks

include("utils.jl")

const ref_url = "https://github.com/JuliaSpacePhysics/VelocityDistributionFunctions.jl/releases/download/v0.2.1/pyspedas_mms_fpi_brst_i.jls"

@testset "Cross-validation with PySPEDAS" begin
    # Reference data generated by: julia --project=ref ref/generate_pyspedas_reference.jl
    # This avoids the slow pyspedas run during normal testing.
    reffile = download_test_data(ref_url)
    saved = deserialize(reffile)
    ref = saved["ref_moments"]
    dists_data = saved["distributions"]
    mag_data = saved["mag_data"]
    scpot_data = saved["scpot_data"]
    ntimes = length(saved["times"])

    # --- Compute moments in Julia for each timestep ---
    _dict2nt(dist) = (
        data = dist["data"], energy = unique(dist["energy"]),
        theta = dist["theta"], dtheta = dist["dtheta"],
        phi = dist["phi"], dphi = dist["dphi"],
        bins = dist["bins"], mass = dist["mass"], charge = dist["charge"],
    )

    dists = _dict2nt.(dists_data)

    moms = plasma_moments(dists, scpot_data; mass = dists[1].mass * 1.0e-10)
    @test moms.density ≈ ref["density"]
    @test moms.avgtemp ≈ ref["avgtemp"]
    @test moms.velocity .* 1.0e-5 ≈ eachrow(ref["velocity"])
    @test moms.flux ≈ eachrow(ref["flux"])
    @test moms.eflux ≈ eachrow(ref["eflux"])
    @test moms.qflux ≈ eachrow(ref["qflux"]) rtol = 1.0e-2
    @test moms.ptens ≈ eachrow(ref["ptens"])
    @test moms.t3 ≈ eachrow(ref["t3"])
    moms = plasma_moments(dists, scpot_data, eachrow(mag_data); mass = dists[1].mass * 1.0e-10)
    @test moms.magt3 ≈ eachrow(ref["magt3"])
    @test moms.symm_ang ≈ ref["symm_ang"]
end
