using Test
using VelocityDistributionFunctions
using VelocityDistributionFunctions: _bin_widths, PROTON_MASS
using Downloads
using JLD2
using Chairmarks

include("utils.jl")

const ref_url = "https://github.com/JuliaSpacePhysics/VelocityDistributionFunctions.jl/releases/download/v0.2.1/pyspedas_mms_fpi_brst_i.jld2"

@testset "_bin_widths" begin
    # Uniform spacing, no wrapping
    @test _bin_widths([0.0, 10.0, 20.0, 30.0]) ≈ [10, 10, 10, 10]
    # Non-uniform spacing
    @test _bin_widths([0.0, 1.0, 4.0]) ≈ [1, 2, 3]
    # Wrapped phi:
    @test _bin_widths([180.0, 240.0, 300.0, 0.0, 60.0, 120.0], 360) ≈ [60, 60, 60, 60, 60, 60]
end

@testset "Cross-validation with PySPEDAS" begin
    # Reference data generated by: julia --project=ref ref/generate_pyspedas_reference.jl
    # This avoids the slow pyspedas run during normal testing.
    reffile = download_test_data(ref_url)
    saved = JLD2.load(reffile)["result"]
    ref = saved["ref"]
    dists_data = saved["distributions"]
    mag_data = saved["mag_data"]
    scpot_data = saved["scpot_data"]
    ntimes = length(saved["times"])
    dists = _dict2nt.(dists_data)

    moms = tmoments(dists, scpot_data)
    @test moms.density ≈ ref["density"]
    @test moms.avgtemp ≈ ref["avgtemp"]
    @test moms.velocity .* 1.0e-5 ≈ eachrow(ref["velocity"])
    @test moms.flux ≈ eachrow(ref["flux"])
    @test moms.eflux ≈ eachrow(ref["eflux"])
    @test moms.qflux ≈ eachrow(ref["qflux"])
    @test moms.ptens ≈ eachrow(ref["ptens"])
    @test moms.t3 ≈ eachrow(ref["t3"])
    moms = tmoments(dists, scpot_data, eachrow(mag_data))
    @test moms.magt3 ≈ eachrow(ref["magt3"])
    @test moms.symm_ang ≈ ref["symm_ang"]

    # Test raw tplot data path (before mms_get_fpi_dist processing).
    # mms_get_fpi_dist applies: theta_gse = colat - 90, phi_gse = (phi + 180) % 360
    mms1_dis_dist_brst = saved["dis_dist_brst"]
    data = mms1_dis_dist_brst["data"]
    theta = mms1_dis_dist_brst["theta"] .- 90
    phi = (mms1_dis_dist_brst["phi"] .+ 180) .% 360
    energy = mms1_dis_dist_brst["energy"]
    moms = tmoments(data, theta, phi, energy, scpot_data, mag_data; edim = 4, tdim = 1, units = :df_cm)
    @info @b tmoments($data, $theta, $phi, $energy, $scpot_data, $mag_data; edim = 4, tdim = 1, units = :df_cm)
    @test moms.density ≈ ref["density"] rtol = 1.0e-6
    @test moms.avgtemp ≈ ref["avgtemp"] rtol = 1.0e-6
    @test moms.velocity .* 1.0e-5 ≈ eachrow(ref["velocity"]) rtol = 1.0e-6
    @test moms.flux ≈ eachrow(ref["flux"]) rtol = 1.0e-6
    @test moms.eflux ≈ eachrow(ref["eflux"]) rtol = 1.0e-6
    @test moms.qflux ≈ eachrow(ref["qflux"]) rtol = 1.0e-5
    @test moms.ptens ≈ eachrow(ref["ptens"]) rtol = 1.0e-6
    @test moms.t3 ≈ eachrow(ref["t3"]) rtol = 1.0e-6
end
